drop table Api
drop table AspNetRoles
drop table AspNetUserClaims
drop table AspNetUserLogins
drop table AspNetUserRoles
drop table AspNetUsers
drop table __MigrationHistory
drop table Band
drop table BandFollowers
drop table BandGenre
drop table Conversation
drop table ConversationConnection
drop table UserGenre
drop table Password
drop table Genre
drop table Member
drop table Message
drop table Friends
drop table Concert
drop table ConcertFollowers