drop table __MigrationHistory
drop table Api
drop table AspNetRoles
drop table AspNetUserClaims
drop table AspNetUserLogins
drop table AspNetUserRoles
drop table AspNetUsers
drop table Band
drop table BandFollowers
drop table BandGenre
drop table BandNotifications
drop table UserGenre
drop table Member
drop table InviteBandNotifications
drop table FriendRequestNotifications
drop table Friends
drop table InviteConcertNotifications
drop table Notifications
drop table Concert
drop table ConcertFollowers
drop table Genre
drop table Password